console.log("server started");

// console.log("exp");
// for (let i = 1; i < 11; i++) {
//   console.log((Math.floor(4 * Math.sqrt(i)) / 5) * 10);
// }

// const factor = 0.1;
// console.log("next level");
// for (let y = 1; y < 11; y++) {
//   console.log(Math.floor(factor * y * 100));
// }

export const player = {
  gold: 1000,
  level: 1,
  nextLevel: 10,
  exp: 0,
  name: "Player 1",
  maps: {
    completed: [],
  },
  enemies: {
    defeated: [],
  },
  bosses: {
    defeated: [],
  },
};

export const heroes = [
  {
    name: "Maeda Yori",
    image: "./assets/characters/blond2.png",
    class: "Sorceress",
    type: "Hero",
    strength: 40,
    intelligence: 3200,
    hp: 1,
    maxHp: 1000,
    mp: 40,
    maxMp: 40,
    weapon: "Sword",
  },
  {
    name: "Vita Norman",
    image: "./assets/characters/red_rid2.png",
    class: "Warrior",
    type: "Hero",
    strength: 10,
    intelligence: 1000,
    hp: 1,
    maxHp: 120,
    mp: 220,
    maxMp: 220,
    weapon: "Sword",
  },
  {
    name: "Eveline Barre",
    image: "./assets/characters/white_hair1.png",
    class: "Warrior",
    type: "Hero",
    strength: 1000,
    intelligence: 7,
    hp: 110,
    maxHp: 110,
    mp: 60,
    maxMp: 60,
    weapon: "Staff",
  },
  {
    name: "Wendy Blair",
    image: "./assets/characters/ginger1.png",
    class: "Black Mage",
    type: "Hero",
    strength: 75,
    intelligence: 12,
    hp: 120,
    maxHp: 120,
    mp: 75,
    maxMp: 75,

    weapon: "Staff",
  },
];

export const enemies = [
  {
    name: "Goblin Ray",
    image: "../assets/characters/goblin1.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 3,
    intelligence: 2,
    hp: 60,
    maxHp: 60,
    weapon: "Dagger",
  },
  {
    name: "Goblin Night",
    image: "../assets/characters/goblin2.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 4,
    intelligence: 1,
    hp: 55,
    maxHp: 55,
    weapon: "Dagger",
  },
  {
    name: "Goblin Night",
    image: "../assets/characters/goblin3.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 5,
    intelligence: 0,
    hp: 65,
    maxHp: 65,
    weapon: "Dagger",
  },
  {
    name: "Goblin Night",
    image: "../assets/characters/goblin4.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 3,
    intelligence: 4,
    hp: 70,
    maxHp: 70,
    weapon: "Dagger",
  },
  {
    name: "Caterpillar",
    image: "../assets/characters/caterpillar.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 12,
    intelligence: 0,
    hp: 100,
    maxHp: 100,
    weapon: "None",
  },
  {
    name: "Monster 1",
    image: "../assets/characters/monster_enemy1.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 9,
    intelligence: 3,
    hp: 120,
    maxHp: 120,
    weapon: "Dagger",
  },
  {
    name: "Monster 2",
    image: "../assets/characters/monster_enemy2.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 8,
    intelligence: 7,
    hp: 130,
    maxHp: 130,
    weapon: "Dagger",
  },
  {
    name: "Monster 3",
    image: "../assets/characters/monster_enemy3.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 14,
    intelligence: 6,
    hp: 250,
    maxHp: 250,
    weapon: "None",
  },
  {
    name: "Monster 4",
    image: "../assets/characters/monster_enemy4.png",
    class: "Normal",
    type: "Enemy",
    level: 5,
    strength: 18,
    intelligence: 1,
    hp: 300,
    maxHp: 300,
    weapon: "None",
  },
  {
    name: "Orc",
    image: "../assets/characters/orc1.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 10,
    intelligence: 0,
    hp: 500,
    maxHp: 500,
    weapon: "None",
  },
  {
    name: "Skeleton 1",
    image: "../assets/characters/skeleton1.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 4,
    intelligence: 4,
    hp: 90,
    maxHp: 90,
    weapon: "Sword",
  },
  {
    name: "Skeleton 2",
    image: "../assets/characters/skeleton2.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 3,
    intelligence: 3,
    hp: 80,
    maxHp: 80,
    weapon: "Sword",
  },
  {
    name: "Skeleton 3",
    image: "../assets/characters/skeleton3.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 5,
    intelligence: 2,
    hp: 110,
    maxHp: 110,
    weapon: "Sword",
  },
  {
    name: "Spider 1",
    image: "../assets/characters/spider1.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 3,
    intelligence: 7,
    hp: 245,
    maxHp: 245,
    weapon: "None",
  },
  {
    name: "Spider 2",
    image: "../assets/characters/spider2.png",
    class: "Normal",
    type: "Enemy",
    level: 6,
    strength: 8,
    intelligence: 12,
    hp: 345,
    maxHp: 345,
    weapon: "None",
  },
  {
    name: "Undead 1",
    image: "../assets/characters/undead1.png",
    class: "Normal",
    type: "Enemy",
    level: 7,
    strength: 10,
    intelligence: 15,
    hp: 345,
    maxHp: 345,
    weapon: "Sword",
  },
  {
    name: "Undead 2",
    image: "../assets/characters/undead2.png",
    class: "Normal",
    type: "Enemy",
    level: 6,
    strength: 8,
    intelligence: 12,
    hp: 320,
    maxHp: 320,
    weapon: "None",
  },
  {
    name: "Undead 3",
    image: "../assets/characters/undead3.png",
    class: "Normal",
    type: "Enemy",
    level: 7,
    strength: 12,
    intelligence: 16,
    hp: 400,
    maxHp: 400,
    weapon: "Axe",
  },
  {
    name: "Witch 1",
    image: "../assets/characters/witch1.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 2,
    intelligence: 16,
    hp: 100,
    maxHp: 100,
    weapon: "Staff",
  },
  {
    name: "Witch 2",
    image: "../assets/characters/witch2.png",
    class: "Normal",
    type: "Enemy",
    level: 5,
    strength: 3,
    intelligence: 18,
    hp: 130,
    maxHp: 130,
    weapon: "Staff",
  },
  {
    name: "Zombie",
    image: "../assets/characters/zombie1.png",
    class: "Normal",
    type: "Enemy",
    level: 8,
    strength: 4,
    intelligence: 0,
    hp: 520,
    maxHp: 520,
    weapon: "Hands",
  },
];
export const items = [
  {
    name: "Healing Potion",
    image: "../assets/items/red_potion1.png",
    type: "Item",
    class: "Cure",
    value: 20,
    price: 50,
  },
  {
    name: "Healing Big Potion",
    image: "../assets/items/red_potion2.png",
    type: "Item",
    class: "Cure",
    value: 60,
    price: 150,
  },
  {
    name: "Mana Potion",
    image: "../assets/items/blue_potion1.png",
    type: "Item",
    class: "Mana",
    value: 20,
    price: 35,
  },
  {
    name: "Mana Big Potion",
    image: "../assets/items/blue_potion2.png",
    type: "Item",
    class: "Mana",
    value: 100,
    price: 135,
  },
  {
    name: "Poison Potion",
    image: "../assets/items/green_potion1.png",
    type: "Item",
    class: "Poison",
    value: 4,
    price: 150,
  },
  {
    name: "Poison Big Potion",
    image: "../assets/items/green_potion2.png",
    type: "Item",
    class: "Poison",
    value: 12,
    price: 300,
  },
  {
    name: "Elixir Potion",
    image: "../assets/items/white_potion1.png",
    type: "Item",
    class: "Elixir",
    value: 100,
    price: 500,
  },
  {
    name: "Reborn Potion",
    image: "../assets/items/purple_potion1.png",
    type: "Item",
    class: "Reborn",
    value: 50,
    price: 10,
  },
  {
    name: "Reborn Rare Potion",
    image: "../assets/items/purple_potion2.png",
    type: "Item",
    class: "Reborn",
    value: 100,
    price: 20,
  },
];

export const bosses = [
  {
    name: "Red Dragon",
    class: "Dragon",
    type: "Boss",
    image: "../assets/characters/dragon1.png",
    level: 20,
    strength: 40,
    intelligence: 70,
    hp: 30,
    maxHp: 3760,
    weapon: "None",
  },
  {
    name: "Giant",
    class: "Giant",
    type: "Boss",
    image: "../assets/characters/giant1.png",
    level: 18,
    strength: 30,
    intelligence: 22,
    hp: 80,
    maxHp: 8000,
    weapon: "None",
  },
  {
    name: "Giant Wolf",
    class: "Giant",
    type: "Boss",
    image: "../assets/characters/giant_wolf1.png",
    level: 15,
    strength: 24,
    intelligence: 12,
    hp: 10,
    maxHp: 900,
    weapon: "None",
  },
];
export const empty = {
  id: "fa404954-b54a-4081-bb68-b12916f763b2",
  name: "Empty",
  type: "Empty",
};
export const start = {
  name: "Start",
  type: "Start",
};

export const maps = [
  {
    name: "Level 1",
    length: 11,
    difficulty: 1,
    type: "Map",
    image: "../assets/maps/map1.jpg",
    positions: [],
    isAvailable: true,
    isCompleted: false,
  },
  {
    name: "Level 2",
    length: 61,
    difficulty: 1,
    type: "Map",
    image: "../assets/maps/map2.jpg",
    positions: [],
    isAvailable: false,
    isCompleted: false,
  },
  {
    name: "Level 3",
    length: 181,
    difficulty: 2,
    type: "Map",
    image: "../assets/maps/map3.jpg",
    positions: [],
    isAvailable: false,
    isCompleted: false,
  },
  {
    name: "Level 4",
    length: 301,
    difficulty: 3,
    type: "Map",
    image: "../assets/maps/map4.jpg",
    positions: [],
    isAvailable: false,
    isCompleted: false,
  },
];

export const weapons = [
  {
    name: "Day Axe",
    image: "../assets/weapons/axe1.png",
    value: 16,
    price: 400,
    type: "Axe",
  },
  {
    name: "Night Axe",
    image: "../assets/weapons/axe2.png",
    value: 18,
    price: 400,
    type: "Axe",
  },
  {
    name: "Dagger",
    image: "../assets/weapons/dagger1.png",
    value: 18,
    price: 400,
    type: "Dagger",
  },
  {
    name: "Sword",
    image: "../assets/weapons/sword1.png",
    value: 21,
    price: 400,
    type: "Sword",
  },
  {
    name: "Sword",
    image: "../assets/weapons/sword2.png",
    value: 23,
    price: 400,
    type: "Sword",
  },
  {
    name: "Sword",
    image: "../assets/weapons/sword3.png",
    value: 25,
    price: 400,
    type: "Sword",
  },
  {
    name: "Staff",
    image: "../assets/weapons/staff1.png",
    value: 30,
    price: 400,
    type: "Staff",
  },
  {
    name: "Pistol",
    image: "../assets/weapons/pistol1.png",
    value: 40,
    price: 400,
    type: "Staff",
  },
];

export const magics = [
  {
    name: "Fire",
    image: "../assets/weapons/pistol1.png",
    value: 35,
    mp: 15,
    type: "Fire",
  },
  {
    name: "Ice",
    image: "../assets/weapons/sword1.png",
    value: 40,
    mp: 30,
    type: "Ice",
  },
  {
    name: "Poison",
    image: "../assets/weapons/sword2.png",
    value: 60,
    mp: 40,
    type: "Poison",
  },
  {
    name: "Darkness",
    image: "../assets/weapons/sword3.png",
    value: 80,
    mp: 50,
    type: "Darkness",
  },
  {
    name: "Electric",
    image: "../assets/weapons/weapon1.png",
    value: 140,
    mp: 60,
    type: "Electric",
  },
];

export const gifts = [
  {
    name: "Random Item",
    image: "../assets/others/treasure1.png",
    type: "Item",
    class: "Gift",
    value: 20,
    price: 50,
  },
  {
    name: "Experience Points",
    image: "../assets/others/gold_bag2.png",
    type: "Experience",
    class: "Gift",
    value: 20,
    price: 50,
  },
  {
    name: "Gold",
    image: "../assets/others/treasure.png",
    type: "Gold",
    class: "Gift",
    value: 20,
    price: 50,
  },
];
