export const player = {
  gold: 1000,
  level: 1,
  expToNextLevel: 110,
  exp: 0,
};

export const heroes = [
  {
    name: "Maeda Yori",
    image: "./assets/japanese1.png",
    class: "Sorceress",
    type: "Hero",
    strength: 1,
    intelligence: 3200,
    hp: 1,
    maxHp: 100,
    mp: 40,
    maxMp: 40,
    isAlive: true,
    weapon: "Sword",
  },
  {
    name: "Vita Norman",
    image: "./assets/red_rid2.png",
    class: "Warrior",
    type: "Hero",
    strength: 1,
    intelligence: 533,
    hp: 1,
    maxHp: 120,
    mp: 30,
    maxMp: 30,
    isAlive: true,
    weapon: "Sword",
  },
  {
    name: "Eveline Barre",
    image: "./assets/alice2.png",
    class: "Warrior",
    type: "Hero",
    strength: 128,
    intelligence: 7,
    hp: 110,
    maxHp: 110,
    mp: 60,
    maxMp: 60,
    isAlive: true,
    weapon: "Staff",
  },
  {
    name: "Wendy Blair",
    image: "./assets/ginger1.png",
    class: "Black Mage",
    type: "Hero",
    strength: 3,
    intelligence: 12,
    hp: 120,
    maxHp: 120,
    mp: 75,
    maxMp: 75,
    isAlive: true,
    weapon: "Staff",
  },
];

export const enemies = [
  {
    name: "Goblin Ray",
    image: "../assets/goblin1.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 3,
    intelligence: 2,
    hp: 60,
    maxHp: 60,
    weapon: "Dagger",
  },
  {
    name: "Goblin Night",
    image: "../assets/goblin2.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 4,
    intelligence: 1,
    hp: 55,
    maxHp: 55,
    weapon: "Dagger",
  },
  {
    name: "Goblin Night",
    image: "../assets/goblin3.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 5,
    intelligence: 0,
    hp: 65,
    maxHp: 65,
    weapon: "Dagger",
  },
  {
    name: "Goblin Night",
    image: "../assets/goblin4.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 3,
    intelligence: 4,
    hp: 70,
    maxHp: 70,
    weapon: "Dagger",
  },
  {
    name: "Caterpillar",
    image: "../assets/caterpillar.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 12,
    intelligence: 0,
    hp: 100,
    maxHp: 100,
    weapon: "None",
  },
  {
    name: "Monster 1",
    image: "../assets/monster_enemy1.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 9,
    intelligence: 3,
    hp: 120,
    maxHp: 120,
    weapon: "Dagger",
  },
  {
    name: "Monster 2",
    image: "../assets/monster_enemy2.png",
    class: "Normal",
    type: "Enemy",
    level: 3,
    strength: 8,
    intelligence: 7,
    hp: 130,
    maxHp: 130,
    weapon: "Dagger",
  },
  {
    name: "Monster 3",
    image: "../assets/monster_enemy3.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 14,
    intelligence: 6,
    hp: 250,
    maxHp: 250,
    weapon: "None",
  },
  {
    name: "Monster 4",
    image: "../assets/monster_enemy4.png",
    class: "Normal",
    type: "Enemy",
    level: 5,
    strength: 18,
    intelligence: 1,
    hp: 300,
    maxHp: 300,
    weapon: "None",
  },
  {
    name: "Orc",
    image: "../assets/orc1.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 10,
    intelligence: 0,
    hp: 500,
    maxHp: 500,
    weapon: "None",
  },
  {
    name: "Skeleton 1",
    image: "../assets/skeleton1.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 4,
    intelligence: 4,
    hp: 90,
    maxHp: 90,
    weapon: "Sword",
  },
  {
    name: "Skeleton 2",
    image: "../assets/skeleton2.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 3,
    intelligence: 3,
    hp: 80,
    maxHp: 80,
    weapon: "Sword",
  },
  {
    name: "Skeleton 3",
    image: "../assets/skeleton3.png",
    class: "Normal",
    type: "Enemy",
    level: 2,
    strength: 5,
    intelligence: 2,
    hp: 110,
    maxHp: 110,
    weapon: "Sword",
  },
  {
    name: "Spider 1",
    image: "../assets/spider1.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 3,
    intelligence: 7,
    hp: 245,
    maxHp: 245,
    weapon: "None",
  },
  {
    name: "Spider 2",
    image: "../assets/spider2.png",
    class: "Normal",
    type: "Enemy",
    level: 6,
    strength: 8,
    intelligence: 12,
    hp: 345,
    maxHp: 345,
    weapon: "None",
  },
  {
    name: "Undead 1",
    image: "../assets/undead1.png",
    class: "Normal",
    type: "Enemy",
    level: 7,
    strength: 10,
    intelligence: 15,
    hp: 345,
    maxHp: 345,
    weapon: "Sword",
  },
  {
    name: "Undead 2",
    image: "../assets/undead2.png",
    class: "Normal",
    type: "Enemy",
    level: 6,
    strength: 8,
    intelligence: 12,
    hp: 320,
    maxHp: 320,
    weapon: "None",
  },
  {
    name: "Undead 3",
    image: "../assets/undead3.png",
    class: "Normal",
    type: "Enemy",
    level: 7,
    strength: 12,
    intelligence: 16,
    hp: 400,
    maxHp: 400,
    weapon: "Axe",
  },
  {
    name: "Witch 1",
    image: "../assets/witch1.png",
    class: "Normal",
    type: "Enemy",
    level: 4,
    strength: 2,
    intelligence: 16,
    hp: 100,
    maxHp: 100,
    weapon: "Staff",
  },
  {
    name: "Witch 2",
    image: "../assets/witch2.png",
    class: "Normal",
    type: "Enemy",
    level: 5,
    strength: 3,
    intelligence: 18,
    hp: 130,
    maxHp: 130,
    weapon: "Staff",
  },
  {
    name: "Zombie",
    image: "../assets/zombie1.png",
    class: "Normal",
    type: "Enemy",
    level: 8,
    strength: 4,
    intelligence: 0,
    hp: 520,
    maxHp: 520,
    weapon: "Hands",
  },
];
export const items = [
  {
    name: "Healing Potion",
    image: "../assets/red_potion1.png",
    type: "Item",
    class: "Cure",
    value: 20,
    price: 50,
  },
  {
    name: "Healing Big Potion",
    image: "../assets/red_potion2.png",
    type: "Item",
    class: "Cure",
    value: 60,
    price: 150,
  },
  {
    name: "Mana Potion",
    image: "../assets/blue_potion1.png",
    type: "Item",
    class: "Mana",
    value: 20,
    price: 35,
  },
  {
    name: "Mana Big Potion",
    image: "../assets/blue_potion2.png",
    type: "Item",
    class: "Mana",
    value: 100,
    price: 135,
  },
  {
    name: "Poison Potion",
    image: "../assets/green_potion1.png",
    type: "Item",
    class: "Poison",
    value: 4,
    price: 150,
  },
  {
    name: "Poison Big Potion",
    image: "../assets/green_potion2.png",
    type: "Item",
    class: "Poison",
    value: 12,
    price: 300,
  },
  {
    name: "Elixir Potion",
    image: "../assets/white_potion1.png",
    type: "Item",
    class: "Elixir",
    value: 100,
    price: 500,
  },
  {
    name: "Reborn Potion",
    image: "../assets/purple_potion1.png",
    type: "Item",
    class: "Reborn",
    value: 50,
    price: 10,
  },
  {
    name: "Reborn Rare Potion",
    image: "../assets/purple_potion2.png",
    type: "Item",
    class: "Reborn",
    value: 100,
    price: 20,
  },
];

export const bosses = [
  {
    name: "Red Dragon",
    class: "Dragon",
    type: "Boss",
    image: "../assets/dragon1.png",
    level: 20,
    strength: 40,
    intelligence: 70,
    hp: 3760,
    maxHp: 3760,
    weapon: "None",
  },
  {
    name: "Giant",
    class: "Giant",
    type: "Boss",
    image: "../assets/giant1.png",
    level: 18,
    strength: 30,
    intelligence: 22,
    hp: 8000,
    maxHp: 8000,
    weapon: "None",
  },
  {
    name: "Giant Wolf",
    class: "Giant",
    type: "Boss",
    image: "../assets/giant_wolf1.png",
    level: 15,
    strength: 24,
    intelligence: 12,
    hp: 900,
    maxHp: 900,
    weapon: "None",
  },
];
export const empty = {
  id: "fa404954-b54a-4081-bb68-b12916f763b2",
  name: "Empty",
  type: "Empty",
};
export const start = {
  name: "Start",
  type: "Start",
};

export const maps = [
  {
    id: "d1f452c1-69ac-4481-a8c7-1c9307e1cedf",
    name: "Level 1",
    length: 6,
    difficulty: 1,
    type: "Map",
    image: "../assets/map1.jpg",
  },
  {
    id: "4ace8d09-1ac8-4ee0-9cc5-c0e0acfe2ebd",
    name: "Level 2",
    length: 61,
    difficulty: 1,
    type: "Map",
    image: "../assets/map2.jpg",
  },
  {
    id: "6da34636-1c05-4dda-b42a-5d6178f0be66",
    name: "Level 3",
    length: 181,
    difficulty: 2,
    type: "Map",
    image: "../assets/map3.jpg",
  },
  {
    id: "83117dfa-1ff3-4649-8cb1-6f8c7d8ecbf6",
    name: "Level 4",
    length: 501,
    difficulty: 3,
    type: "Map",
    image: "../assets/map4.jpg",
  },
];

export const weapons = [
  {
    name: "Day Axe",
    image: "../assets/axe1.png",
    value: 16,
    price: 400,
    type: "Axe",
  },
  {
    name: "Night Axe",
    image: "../assets/axe2.png",
    value: 18,
    price: 400,
    type: "Axe",
  },
  {
    name: "Dagger",
    image: "../assets/dagger1.png",
    value: 18,
    price: 400,
    type: "Dagger",
  },
  {
    name: "Sword",
    image: "../assets/sword1.png",
    value: 21,
    price: 400,
    type: "Sword",
  },
  {
    name: "Sword",
    image: "../assets/sword2.png",
    value: 23,
    price: 400,
    type: "Sword",
  },
  {
    name: "Sword",
    image: "../assets/sword3.png",
    value: 25,
    price: 400,
    type: "Sword",
  },
  {
    name: "Staff",
    image: "../assets/staff1.png",
    value: 30,
    price: 400,
    type: "Staff",
  },
  {
    name: "Pistol",
    image: "../assets/pistol1.png",
    value: 40,
    price: 400,
    type: "Staff",
  },
];
